# roles/mariadb/tasks/users.yml
---
- name: copy script file
  copy:
    src: ../../script.sh
    dest: /home/ec2-user/script.sh
    owner: ec2-user
    group: ec2-user
    mode: 0755 
- name: run a shell script
  shell: sudo /home/ec2-user/script.sh
  args: 
    chdir: /home/ec2-user/
